#!/usr/bin/env node
'use strict';

var spawn = require('@ryanburnette/spawn-in-parallel');

spawn([
  'npx http-server dist/',
  'npx webpack --config webpack.development.js --watch --colors',
  'scripts/watch'
]);
