#!/usr/bin/env node
'use strict';

var spawn = require('@ryanburnette/spawn-in-parallel');

spawn([
	'npx webpack --config webpack.development.js --watch --colors',
	'scripts/watch',
	{
		cmd: 'caddy run --config Caddyfile.development',
		opts: {
			shell: true,
			env: {
				PATH: process.env.PATH,
				HOME: process.env.HOME
			}
		}
	}
]);
